version: '3'
services:
    app:
        build: .
        image: dogs-fact
        #container_name: dogs-fact

        #volumes:
        #    - ./data:/app/data
        #    - ./logs:/app/logs

        #ports:
        #    - "${HTTP_PORT:-5000}:5000"
        expose:
             - "5000"
 
        #command: sleep 3
 
    proxy:
        depends_on:
            - app

        build:
            context: .
            dockerfile: Dockerfile-scale

        image: fact-proxy
        container_name: fact-proxy

        volumes:
            - /tmp/dogs-fact-proxy:/var/log/nginx
        #    - ./nginx.conf:/etc/nginx/nginx.conf:ro

        ports:
            - "${HTTP_PORT:-5000}:80"

