version: '3'
services:
    app:
        image: dogs-fact
        container_name: dogs-fact
        build: .
        ports:
            - "${HTTP_PORT:-5000}:5000"

        #volumes:
        #    - ./data:/app/data
        #    - ./logs:/app/logs
 
